import type { Property, Owner } from './definitions';

export const OWNERS: Owner[] = [
  {
    idOwner: 'owner1',
    name: 'Alexander Moncada',
    address: '123 Main St, Anytown, USA',
    photo: 'https://picsum.photos/seed/owner1/100/100',
    birthday: '1980-05-15',
  },
  {
    idOwner: 'owner2',
    name: 'Jane Smith',
    address: '456 Oak Ave, Someville, USA',
    photo: 'https://picsum.photos/seed/owner2/100/100',
    birthday: '1992-11-20',
  },
];

export const PROPERTIES: Property[] = [
  {
    idProperty: 'prop1',
    name: 'Modern Downtown Apartment',
    address: '101 City Center Plaza, Urbania',
    price: 2200,
    year: 2020,
    imageUrl: 'https://picsum.photos/seed/prop1/800/600',
    idOwner: 'owner1',
    description: 'A stunning modern apartment in the heart of the city. Features floor-to-ceiling windows, a gourmet kitchen, and access to a rooftop pool. Perfect for professionals.',
    rooms: 2,
    bathrooms: 2,
    area: 1100,
    location: { lat: 34.0522, lng: -118.2437 },
  },
  {
    idProperty: 'prop2',
    name: 'Spacious Suburban House',
    address: '255 Green Valley Rd, Suburbia',
    price: 3500,
    year: 2015,
    imageUrl: 'https://picsum.photos/seed/prop2/800/600',
    idOwner: 'owner2',
    description: 'A beautiful and spacious family home in a quiet suburban neighborhood. Includes a large backyard with a deck, a two-car garage, and a newly renovated master suite.',
    rooms: 4,
    bathrooms: 3,
    area: 2400,
    location: { lat: 34.1522, lng: -118.3437 },
  },
  {
    idProperty: 'prop3',
    name: 'Chic Industrial Loft',
    address: '77 Warehouse District, Metroville',
    price: 1950,
    year: 2018,
    imageUrl: 'https://picsum.photos/seed/prop3/800/600',
    idOwner: 'owner1',
    description: 'Live in style in this chic industrial loft with exposed brick walls, high ceilings, and polished concrete floors. The open floor plan is perfect for entertaining.',
    rooms: 1,
    bathrooms: 1,
    area: 950,
    location: { lat: 34.0422, lng: -118.2537 },
  },
  {
    idProperty: 'prop4',
    name: 'Luxury Beachfront Villa',
    address: '1 Ocean View Dr, Coastline City',
    price: 7500,
    year: 2022,
    imageUrl: 'https://picsum.photos/seed/prop4/800/600',
    idOwner: 'owner2',
    description: 'Experience ultimate luxury in this breathtaking beachfront villa. Enjoy private beach access, an infinity pool, and panoramic ocean views from every room.',
    rooms: 5,
    bathrooms: 6,
    area: 4500,
    location: { lat: 33.9922, lng: -118.4537 },
  },
  {
    idProperty: 'prop5',
    name: 'Cozy Countryside Cottage',
    address: '987 Meadowsweet Lane, Ruralton',
    price: 1500,
    year: 1998,
    imageUrl: 'https://picsum.photos/seed/prop5/800/600',
    idOwner: 'owner1',
    description: 'Escape the city to this charming and cozy cottage. Features a beautiful garden, a wood-burning fireplace, and serene views of the countryside. A perfect peaceful retreat.',
    rooms: 3,
    bathrooms: 2,
    area: 1600,
    location: { lat: 34.2522, lng: -118.1437 },
  },
];
